# Assignment: Ionosphere Data Problem

### Dataset Description: 

This radar data was collected by a system in Goose Bay, Labrador. This system consists of a phased array of 16 high-frequency antennas with a total transmitted power on the order of 6.4 kilowatts. See the paper for more details. The targets were free electrons in the ionosphere. "Good" radar returns are those showing evidence of some type of structure in the ionosphere. "Bad" returns are those that do not; their signals pass through the ionosphere.

Received signals were processed using an autocorrelation function whose arguments are the time of a pulse and the pulse number. There were 17 pulse numbers for the Goose Bay system. Instances in this databse are described by 2 attributes per pulse number, corresponding to the complex values returned by the function resulting from the complex electromagnetic signal.

### Attribute Information:

- All 34 are continuous
- The 35th attribute is either "good" or "bad" according to the definition summarized above. This is a binary classification task.

 <br><br>

<table border="1"  cellpadding="6">
	<tbody>
        <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Data Set Characteristics:&nbsp;&nbsp;</b></p></td>
		<td><p class="normal">Multivariate</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Instances:</b></p></td>
		<td><p class="normal">351</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Area:</b></p></td>
		<td><p class="normal">Physical</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">
    <tbody>
        <tr>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Attribute Characteristics:</b></p></td>
            <td><p class="normal">Integer,Real</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Number of Attributes:</b></p></td>
            <td><p class="normal">34</p></td>
            <td bgcolor="#DDEEFF"><p class="normal"><b>Date Donated</b></p></td>
            <td><p class="normal">N/A</p></td>
        </tr>
     </tbody>
    </table>
<table border="1" cellpadding="6">	
    <tbody>
    <tr>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Associated Tasks:</b></p></td>
		<td><p class="normal">Classification</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Missing Values?</b></p></td>
		<td><p class="normal">N/A</p></td>
		<td bgcolor="#DDEEFF"><p class="normal"><b>Number of Web Hits:</b></p></td>
		<td><p class="normal">N/A</p></td>
	</tr>
    </tbody>
    </table>

### WORKFLOW :
- Load Data
- Check Missing Values ( If Exist ; Fill each record with mean of its feature ) or any usless column.
- Shuffle the data if needed.
- Standardized the Input Variables. **Hint**: Centeralized the data
- Split into 60 and 40 ratio.
- Encode labels.
- Model : 1 hidden layers including 16 unit.
- Compilation Step (Note : Its a Binary problem , select loss , metrics according to it)
- Train the Model with Epochs (100).
- If the model gets overfit tune your model by changing the units , No. of layers , epochs , add dropout layer or add Regularizer according to the need .
- Prediction should be > **92%**
- Evaluation Step
- Prediction

# Load Data:
[Click Here to Download DataSet](https://github.com/ramsha275/ML_Datasets/blob/main/ionosphere_data.csv)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ionosphere_data.csv to ionosphere_data.csv

In [3]:
data = pd.read_csv('ionosphere_data.csv')

In [4]:
data.shape

(351, 35)

In [5]:
data.head()

   feature1  feature2  feature3  ...  feature33  feature34  label
0         1         0   0.99539  ...    0.18641   -0.45300      g
1         1         0   1.00000  ...   -0.13738   -0.02447      b
2         1         0   1.00000  ...    0.56045   -0.38238      g
3         1         0   1.00000  ...   -0.32382    1.00000      b
4         1         0   1.00000  ...   -0.04608   -0.65697      g

[5 rows x 35 columns]

In [6]:
data.dtypes

feature1       int64
feature2       int64
feature3     float64
feature4     float64
feature5     float64
feature6     float64
feature7     float64
feature8     float64
feature9     float64
feature10    float64
feature11    float64
feature12    float64
feature13    float64
feature14    float64
feature15    float64
feature16    float64
feature17    float64
feature18    float64
feature19    float64
feature20    float64
feature21    float64
feature22    float64
feature23    float64
feature24    float64
feature25    float64
feature26    float64
feature27    float64
feature28    float64
feature29    float64
feature30    float64
feature31    float64
feature32    float64
feature33    float64
feature34    float64
label         object
dtype: object

In [7]:
data.describe().T

           count      mean       std  min       25%      50%       75%  max
feature1   351.0  0.891738  0.311155  0.0  1.000000  1.00000  1.000000  1.0
feature2   351.0  0.000000  0.000000  0.0  0.000000  0.00000  0.000000  0.0
feature3   351.0  0.641342  0.497708 -1.0  0.472135  0.87111  1.000000  1.0
feature4   351.0  0.044372  0.441435 -1.0 -0.064735  0.01631  0.194185  1.0
feature5   351.0  0.601068  0.519862 -1.0  0.412660  0.80920  1.000000  1.0
feature6   351.0  0.115889  0.460810 -1.0 -0.024795  0.02280  0.334655  1.0
feature7   351.0  0.550095  0.492654 -1.0  0.211310  0.72873  0.969240  1.0
feature8   351.0  0.119360  0.520750 -1.0 -0.054840  0.01471  0.445675  1.0
feature9   351.0  0.511848  0.507066 -1.0  0.087110  0.68421  0.953240  1.0
feature10  351.0  0.181345  0.483851 -1.0 -0.048075  0.01829  0.534195  1.0
feature11  351.0  0.476183  0.563496 -1.0  0.021120  0.66798  0.957895  1.0
feature12  351.0  0.155040  0.494817 -1.0 -0.065265  0.02825  0.482375  1.0
feature13  351.0  0.400801  0.622186 -1.0  0.000000  0.64407  0.955505  1.0
feature14  351.0  0.093414  0.494873 -1.0 -0.073725  0.03027  0.374860  1.0
feature15  351.0  0.344159  0.652828 -1.0  0.000000  0.60194  0.919330  1.0
feature16  351.0  0.071132  0.458371 -1.0 -0.081705  0.00000  0.308975  1.0
feature17  351.0  0.381949  0.618020 -1.0  0.000000  0.59091  0.935705  1.0
feature18  351.0 -0.003617  0.496762 -1.0 -0.225690  0.00000  0.195285  1.0
feature19  351.0  0.359390  0.626267 -1.0  0.000000  0.57619  0.899265  1.0
feature20  351.0 -0.024025  0.519076 -1.0 -0.234670  0.00000  0.134370  1.0
feature21  351.0  0.336695  0.609828 -1.0  0.000000  0.49909  0.894865  1.0
feature22  351.0  0.008296  0.518166 -1.0 -0.243870  0.00000  0.188760  1.0
feature23  351.0  0.362475  0.603767 -1.0  0.000000  0.53176  0.911235  1.0
feature24  351.0 -0.057406  0.527456 -1.0 -0.366885  0.00000  0.164630  1.0
feature25  351.0  0.396135  0.578451 -1.0  0.000000  0.55389  0.905240  1.0
feature26  351.0 -0.071187  0.508495 -1.0 -0.332390 -0.01505  0.156765  1.0
feature27  351.0  0.541641  0.516205 -1.0  0.286435  0.70824  0.999945  1.0
feature28  351.0 -0.069538  0.550025 -1.0 -0.443165 -0.01769  0.153535  1.0
feature29  351.0  0.378445  0.575886 -1.0  0.000000  0.49664  0.883465  1.0
feature30  351.0 -0.027907  0.507974 -1.0 -0.236885  0.00000  0.154075  1.0
feature31  351.0  0.352514  0.571483 -1.0  0.000000  0.44277  0.857620  1.0
feature32  351.0 -0.003794  0.513574 -1.0 -0.242595  0.00000  0.200120  1.0
feature33  351.0  0.349364  0.522663 -1.0  0.000000  0.40956  0.813765  1.0
feature34  351.0  0.014480  0.468337 -1.0 -0.165350  0.00000  0.171660  1.0

In [12]:
data.isnull().any()

feature1     False
feature3     False
feature4     False
feature5     False
feature6     False
feature7     False
feature8     False
feature9     False
feature10    False
feature11    False
feature12    False
feature13    False
feature14    False
feature15    False
feature16    False
feature17    False
feature18    False
feature19    False
feature20    False
feature21    False
feature22    False
feature23    False
feature24    False
feature25    False
feature26    False
feature27    False
feature28    False
feature29    False
feature30    False
feature31    False
feature32    False
feature33    False
feature34    False
label        False
dtype: bool

In [8]:
for feature in data:
    print(feature)
    print(len(data[feature].unique()))

feature1
2
feature2
1
feature3
219
feature4
269
feature5
204
feature6
259
feature7
231
feature8
260
feature9
244
feature10
267
feature11
246
feature12
269
feature13
238
feature14
266
feature15
234
feature16
270
feature17
254
feature18
280
feature19
254
feature20
266
feature21
248
feature22
265
feature23
248
feature24
264
feature25
256
feature26
273
feature27
256
feature28
281
feature29
244
feature30
266
feature31
243
feature32
263
feature33
245
feature34
263
label
2

In [9]:
data['feature2'].unique()

array([0])

In [10]:
data.drop(data.columns[1], inplace=True, axis=1)

In [20]:
data[['feature1']]=data[['feature1']].astype('float64')

In [21]:
data.head()

   feature1  feature3  feature4  ...  feature33  feature34  label
0       1.0   0.99539  -0.05889  ...    0.18641   -0.45300      1
1       1.0   1.00000  -0.18829  ...   -0.13738   -0.02447      0
2       1.0   1.00000  -0.03365  ...    0.56045   -0.38238      1
3       1.0   1.00000  -0.45161  ...   -0.32382    1.00000      0
4       1.0   1.00000  -0.02401  ...   -0.04608   -0.65697      1

[5 rows x 34 columns]

In [23]:
data['label'] = [1 if lbl == 'g' else 0 for lbl in data['label']]

In [24]:
data['label']=data['label'].astype('float64')

In [25]:
data.head()

   feature1  feature3  feature4  ...  feature33  feature34  label
0       1.0   0.99539  -0.05889  ...    0.18641   -0.45300    0.0
1       1.0   1.00000  -0.18829  ...   -0.13738   -0.02447    0.0
2       1.0   1.00000  -0.03365  ...    0.56045   -0.38238    0.0
3       1.0   1.00000  -0.45161  ...   -0.32382    1.00000    0.0
4       1.0   1.00000  -0.02401  ...   -0.04608   -0.65697    0.0

[5 rows x 34 columns]

In [26]:
train_data = data.sample(frac= 0.6, random_state=125)
test_data = data.drop(train_data.index)

In [27]:
train_label = train_data.iloc[:,-1]
train_data = train_data.iloc[:,0:-1]
test_label = test_data.iloc[:,-1]
test_data = test_data.iloc[:,0:-1]

In [28]:
train_data.head()

     feature1  feature3  feature4  ...  feature32  feature33  feature34
270       1.0   1.00000   0.08013  ...   -0.03464    0.92226   -0.03673
116       1.0   1.00000  -0.14754  ...   -0.44262    0.49180   -0.06557
135       1.0   0.89706   0.38235  ...   -0.50735   -0.28676   -0.56618
91        1.0   0.84557  -0.08580  ...   -0.78170   -0.18494   -0.59867
100       1.0   1.00000  -1.00000  ...   -1.00000    0.00000    0.00000

[5 rows x 33 columns]

In [29]:
train_label

270    0.0
116    0.0
135    0.0
91     0.0
100    0.0
      ...
213    0.0
161    0.0
141    0.0
59     0.0
113    0.0
Name: label, Length: 211, dtype: float64

In [30]:
mean=train_data.mean(axis=0)
std=train_data.std(axis=0)

train_data-=mean
train_data/=std

test_data-=mean
test_data/=std

In [36]:
from keras import models
from keras import layers
model=models.Sequential()
model.add(layers.Dense(24,activation='relu' ,input_shape=(33,)))
model.add(layers.Dense(16,activation='relu'))
model.add(layers.Dense(8,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

In [37]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

In [38]:
model.fit(train_data,train_label,epochs=20,batch_size=1,validation_split=0.2)

Epoch 1/20
168/168 [==============================] - 1s 3ms/step - loss: 0.7383 - accuracy: 0.5293 - val_loss: 0.1787 - val_accuracy: 1.0000
Epoch 2/20
168/168 [==============================] - 0s 2ms/step - loss: 0.1151 - accuracy: 1.0000 - val_loss: 0.0043 - val_accuracy: 1.0000
Epoch 3/20
168/168 [==============================] - 0s 2ms/step - loss: 0.0032 - accuracy: 1.0000 - val_loss: 5.2793e-05 - val_accuracy: 1.0000
Epoch 4/20
168/168 [==============================] - 0s 2ms/step - loss: 8.0564e-05 - accuracy: 1.0000 - val_loss: 1.4653e-06 - val_accuracy: 1.0000
Epoch 5/20
168/168 [==============================] - 0s 2ms/step - loss: 1.5049e-06 - accuracy: 1.0000 - val_loss: 1.2672e-07 - val_accuracy: 1.0000
Epoch 6/20
168/168 [==============================] - 0s 2ms/step - loss: 5.4310e-07 - accuracy: 1.0000 - val_loss: 1.4346e-08 - val_accuracy: 1.0000
Epoch 7/20
168/168 [==============================] - 0s 2ms/step - loss: 1.2742e-08 - accuracy: 1.0000 - val_loss: 3.2411e-09 - val_accuracy: 1.0000
Epoch 8/20
168/168 [==============================] - 0s 2ms/step - loss: 6.4717e-09 - accuracy: 1.0000 - val_loss: 1.5682e-09 - val_accuracy: 1.0000
Epoch 9/20
168/168 [==============================] - 0s 2ms/step - loss: 5.1075e-09 - accuracy: 1.0000 - val_loss: 8.7913e-10 - val_accuracy: 1.0000
Epoch 10/20
168/168 [==============================] - 0s 2ms/step - loss: 1.6630e-09 - accuracy: 1.0000 - val_loss: 5.8290e-10 - val_accuracy: 1.0000
Epoch 11/20
168/168 [==============================] - 0s 2ms/step - loss: 6.2372e-10 - accuracy: 1.0000 - val_loss: 4.1630e-10 - val_accuracy: 1.0000
Epoch 12/20
168/168 [==============================] - 0s 2ms/step - loss: 6.0703e-10 - accuracy: 1.0000 - val_loss: 3.1906e-10 - val_accuracy: 1.0000
Epoch 13/20
168/168 [==============================] - 0s 2ms/step - loss: 4.3863e-10 - accuracy: 1.0000 - val_loss: 2.5522e-10 - val_accuracy: 1.0000
Epoch 14/20
168/168 [==============================] - 0s 2ms/step - loss: 2.4755e-10 - accuracy: 1.0000 - val_loss: 2.1148e-10 - val_accuracy: 1.0000
Epoch 15/20
168/168 [==============================] - 0s 2ms/step - loss: 1.3488e-10 - accuracy: 1.0000 - val_loss: 1.7939e-10 - val_accuracy: 1.0000
Epoch 16/20
168/168 [==============================] - 0s 2ms/step - loss: 1.2016e-10 - accuracy: 1.0000 - val_loss: 1.5562e-10 - val_accuracy: 1.0000
Epoch 17/20
168/168 [==============================] - 0s 2ms/step - loss: 1.8089e-10 - accuracy: 1.0000 - val_loss: 1.3693e-10 - val_accuracy: 1.0000
Epoch 18/20
168/168 [==============================] - 0s 2ms/step - loss: 6.7481e-11 - accuracy: 1.0000 - val_loss: 1.2180e-10 - val_accuracy: 1.0000
Epoch 19/20
168/168 [==============================] - 0s 2ms/step - loss: 1.7682e-10 - accuracy: 1.0000 - val_loss: 1.0985e-10 - val_accuracy: 1.0000
Epoch 20/20
168/168 [==============================] - 0s 2ms/step - loss: 1.2699e-10 - accuracy: 1.0000 - val_loss: 9.9817e-11 - val_accuracy: 1.0000

In [39]:
model.evaluate(test_data,test_label)

5/5 [==============================] - 0s 3ms/step - loss: 8.5972e-10 - accuracy: 1.0000

[8.597177414415569e-10, 1.0]

In [42]:
def build_model():
  model=models.Sequential()
  model.add(layers.Dense(24,activation='relu' ,input_shape=(33,)))
  model.add(layers.Dense(16,activation='relu'))
  model.add(layers.Dense(8,activation='relu'))
  model.add(layers.Dense(1,activation='sigmoid'))
  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [43]:
k=4
num_val_samples = len(train_data) // k
num_epochs = 10
all_scores = []
for i in range(k):
 print('processing fold #', i)

 # Prepare the validation data: data from partition # k
 val_data = train_data[i * num_val_samples: (i + 1) * num_val_samples]
 val_targets = train_label[i * num_val_samples: (i + 1) * num_val_samples]


 # Prepare the training data: data from all other partitions
 partial_train_data = np.concatenate([train_data[:i * num_val_samples],train_data[(i + 1) * num_val_samples:]],axis=0)
 partial_train_targets = np.concatenate([train_label[:i * num_val_samples],train_label[(i + 1) * num_val_samples:]],axis=0)


 # Build the Keras model (already compiled)
 model = build_model()
 # Train the model (in silent mode, verbose=0)
 model.fit(partial_train_data, partial_train_targets,epochs=num_epochs, batch_size=1, verbose=1)
 # Evaluate the model on the validation data
 all_scores.append(model.evaluate(val_data, val_targets, verbose=1))

processing fold # 0
Epoch 1/10
159/159 [==============================] - 1s 1ms/step - loss: 0.1492 - accuracy: 1.0000
Epoch 2/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 3/10
159/159 [==============================] - 0s 1ms/step - loss: 2.6112e-05 - accuracy: 1.0000
Epoch 4/10
159/159 [==============================] - 0s 1ms/step - loss: 6.2191e-07 - accuracy: 1.0000
Epoch 5/10
159/159 [==============================] - 0s 1ms/step - loss: 1.0810e-07 - accuracy: 1.0000
Epoch 6/10
159/159 [==============================] - 0s 1ms/step - loss: 4.4031e-09 - accuracy: 1.0000
Epoch 7/10
159/159 [==============================] - 0s 1ms/step - loss: 1.1054e-09 - accuracy: 1.0000
Epoch 8/10
159/159 [==============================] - 0s 1ms/step - loss: 1.9196e-09 - accuracy: 1.0000
Epoch 9/10
159/159 [==============================] - 0s 1ms/step - loss: 4.8230e-10 - accuracy: 1.0000
Epoch 10/10
159/159 [==============================] - 0s 1ms/step - loss: 8.4788e-10 - accuracy: 1.0000
2/2 [==============================] - 0s 5ms/step - loss: 3.9553e-10 - accuracy: 1.0000
processing fold # 1
Epoch 1/10
159/159 [==============================] - 1s 1ms/step - loss: 0.5596 - accuracy: 0.6994
Epoch 2/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0466 - accuracy: 1.0000
Epoch 3/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 4/10
159/159 [==============================] - 0s 1ms/step - loss: 2.5509e-04 - accuracy: 1.0000
Epoch 5/10
159/159 [==============================] - 0s 1ms/step - loss: 3.0440e-05 - accuracy: 1.0000
Epoch 6/10
159/159 [==============================] - 0s 1ms/step - loss: 9.8211e-07 - accuracy: 1.0000
Epoch 7/10
159/159 [==============================] - 0s 1ms/step - loss: 2.5119e-07 - accuracy: 1.0000
Epoch 8/10
159/159 [==============================] - 0s 1ms/step - loss: 8.1550e-09 - accuracy: 1.0000
Epoch 9/10
159/159 [==============================] - 0s 1ms/step - loss: 3.6857e-09 - accuracy: 1.0000
Epoch 10/10
159/159 [==============================] - 0s 1ms/step - loss: 9.8999e-10 - accuracy: 1.0000
2/2 [==============================] - 0s 7ms/step - loss: 1.1671e-07 - accuracy: 1.0000
processing fold # 2
Epoch 1/10
159/159 [==============================] - 1s 1ms/step - loss: 0.4727 - accuracy: 0.8394
Epoch 2/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0165 - accuracy: 1.0000
Epoch 3/10
159/159 [==============================] - 0s 1ms/step - loss: 7.5363e-04 - accuracy: 1.0000
Epoch 4/10
159/159 [==============================] - 0s 1ms/step - loss: 3.7417e-05 - accuracy: 1.0000
Epoch 5/10
159/159 [==============================] - 0s 1ms/step - loss: 1.4827e-06 - accuracy: 1.0000
Epoch 6/10
159/159 [==============================] - 0s 1ms/step - loss: 1.2524e-07 - accuracy: 1.0000
Epoch 7/10
159/159 [==============================] - 0s 1ms/step - loss: 9.8545e-09 - accuracy: 1.0000
Epoch 8/10
159/159 [==============================] - 0s 1ms/step - loss: 2.4402e-09 - accuracy: 1.0000
Epoch 9/10
159/159 [==============================] - 0s 1ms/step - loss: 1.0426e-09 - accuracy: 1.0000
Epoch 10/10
159/159 [==============================] - 0s 1ms/step - loss: 7.9315e-10 - accuracy: 1.0000
WARNING:tensorflow:5 out of the last 870 calls to <function Model.make_test_function.<locals>.test_function at 0x7fbedcb45200> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 5ms/step - loss: 2.3593e-09 - accuracy: 1.0000
processing fold # 3
Epoch 1/10
159/159 [==============================] - 1s 1ms/step - loss: 0.6453 - accuracy: 0.5703
Epoch 2/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0740 - accuracy: 1.0000
Epoch 3/10
159/159 [==============================] - 0s 1ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 4/10
159/159 [==============================] - 0s 1ms/step - loss: 4.9635e-05 - accuracy: 1.0000
Epoch 5/10
159/159 [==============================] - 0s 1ms/step - loss: 1.2445e-05 - accuracy: 1.0000
Epoch 6/10
159/159 [==============================] - 0s 1ms/step - loss: 7.7853e-07 - accuracy: 1.0000
Epoch 7/10
159/159 [==============================] - 0s 1ms/step - loss: 4.8493e-07 - accuracy: 1.0000
Epoch 8/10
159/159 [==============================] - 0s 1ms/step - loss: 1.1029e-07 - accuracy: 1.0000
Epoch 9/10
159/159 [==============================] - 0s 1ms/step - loss: 9.6401e-09 - accuracy: 1.0000
Epoch 10/10
159/159 [==============================] - 0s 1ms/step - loss: 2.7934e-09 - accuracy: 1.0000
WARNING:tensorflow:5 out of the last 12 calls to <function Model.make_test_function.<locals>.test_function at 0x7fbee7e804d0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 [==============================] - 0s 5ms/step - loss: 3.5500e-09 - accuracy: 1.0000

In [44]:
all_scores

[[3.955311356218516e-10, 1.0],
 [1.1670962152265929e-07, 1.0],
 [2.3592601205990604e-09, 1.0],
 [3.5500316020176115e-09, 1.0]]

In [45]:
model.evaluate(test_data,test_label)

5/5 [==============================] - 0s 3ms/step - loss: 1.0836e-07 - accuracy: 1.0000

[1.0836452446483236e-07, 1.0]

In [48]:
model.evaluate(data.iloc[1:5, :-1],data.iloc[1:5,-1])

1/1 [==============================] - 0s 17ms/step - loss: 8.5821e-08 - accuracy: 1.0000

[8.582050270433683e-08, 1.0]